# Generated by Django 2.1.5 on 2019-02-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_create_post', 'Can post blog')]},
        ),
    ]
