# Generated by Django 2.1.5 on 2019-02-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190222_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_create_post', 'Can post blog'), ('can_update_post', 'Can update blog post')]},
        ),
    ]
